[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_runtime = "nodejs18.x"
  directory = "server" # Ye aapke server.ts ko function ki tarah chalayega

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200